### ISSUE TITLE
No Mobile project included

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/PartsUnlimited#106]
Hi,

Please share the mobile solution too! There's no mobile project included in this repo.

Thanks,
Srivatsa

**Comment by julienstroheker** [comment]
@nzthiago can you help on that one ?

**Comment by nzthiago** [comment]
Ooops, turns out I had closed a PR instead of merging it. @SrivatsaMarichi you should see a PartsUnlimited.Mobile.sln in the repo now
