### ISSUE TITLE
Deployment Failure due to Microsoft.Insights/Components

### ISSUE THREAD

**Issue by HernanCote** [Microsoft/PartsUnlimited#118]
I'm having issues when I try to deploy the App with "Azure Resource Group Deployment" Task as indicated in the labs.

I'm getting the following error message:

Resource Microsoft.Insights/components 'pudncorehcote-StagingInsights' failed with message '{
  "error": {
    "code": "MissingRegistrationForLocation",
    "message": "The subscription is not registered for the resource type 'components' in the location 'Central US'. Please re-register for this provider in order to have access to this location."
}

Its the same error for the dev and production environments. Any toughs on what is causing the error?

**Comment by HernanCote** [comment]
Fixed, It seems Microsoft.Insights/components is not available in Central US. Changed the location to South Central US and worked.

**Comment by dtzar** [comment]
Sorry about that @HernanCote - this is resolved in #118
