### ISSUE TITLE
Documentation Issue on the Manual Deployment

### ISSUE THREAD

**Issue by mountainbrother** [Microsoft/PartsUnlimited#130]
I go the next phase from the HOL  and try the Manual Deployment.
I run always in an build error at the src/Website at the npm install task --> 9009

I could fixed the error after I find out, that the npm install command only works with admin rights in the shell.
After I start VS2017 as an admin I was able to run successfully the build solution command and I could publish it to azure.
Please extent the docu with the run as admin VS2017  
THX

**Comment by eamkel** [comment]
Thanks for posting, added a step at the start of the manual deployment task to start VS2017 as admin.

Thanks Again,

**Comment by mountainbrother** [comment]
done! Thx @eamkel
