### ISSUE TITLE
The value for the template parameter '_artifactsLocation' is not provided

### ISSUE THREAD

**Issue by winterwy** [Microsoft/PartsUnlimited#131]
Hi,

I am a new guy for devops. 
when I followed this tutorial step by step, I met the above error. 
It happened on "Azure Deployment:Create Or Update Resource Group action on $(ResourceGroupName)" in "Continuous Deployment" chapter. 
Can anyone give me a help?

Thanks a lot,
Thomas Yang

**Comment by eamkel** [comment]
Hi Thomas,
 
Were you able to get the CI build working on the CI lab task? that configures the application drop artifact. If that is running successfully, then were you able to add in the publish artifact task for the ARMTemplates? were both of those artifacts generated successfully when you ran the CI build?

If so, then you need to look at the first task in the CD release, were it deploys the infrastructure, and if you are pointing to the correct artifact, for that first task it uses the ARM Templates to deploy the infrastructure.

Have a look at those items in order and see up to where its running fine and where specifically its breaking down and let us know.

Thanks,
Eamonn

**Comment by winterwy** [comment]
Hi Eamonn,
Thank you for your reply.

I successfully get CI build working and get artifacts for ARMTemplates.
In CD release first task I also point to the correct artifact as below.

![image](https://user-images.githubusercontent.com/32636799/31582133-4bbc0d7e-b1c7-11e7-8633-c370f03c508f.png)

However, I still get this error. 

Regards,
THomas Yang

**Comment by eamkel** [comment]
Hi Thomas, 

And can you download and explore the artifacts once they are generated in the CI build?

If they are being generated and are accessible in the CI build, one thing you could try is to shorten the path name to access them, rather than a long one "restore, build test, copy and publish" with commas, just use a single word. The task steps would use the folder names "drop" and "ARMTemplates", for the artifact locations, the "restore, build test, copy and publish" name is just used in the actual task name. So it may be worth changing that in your config.

Thanks Again,
Eamonn

**Comment by winterwy** [comment]
Hi Eamonn,

Thank you very much for your magical suggestion.

after I change source alias to short and single name, the deployment successfully finishes. 
However, my subscription expired, I have to apply for new one to finish the whole deployment. 

Thanks again. 
Best regards,
Thomas

**Comment by winterwy** [comment]
Hi Eamonn

I am sorry to open this issue again.
Today I just apply new subscription for azure and try it again in my new subscription.
It failed again with the same error message "The value for the template parameter '_artifactsLocation' is not provided". 
this time I check it that I can download and explore artifacts. 
![image](https://user-images.githubusercontent.com/32636799/31767799-4685276a-b518-11e7-8fd8-352561f7eacc.png)
the path name is also short.
![image](https://user-images.githubusercontent.com/32636799/31767821-61d921a6-b518-11e7-9de3-2aec2854ad74.png)

I think last time the release did not go through because my subscription is expired. 

Now this really make me upset. 
Could you please help me in your first convenience?

Thanks a lot,
Thomas Yang

**Comment by eamkel** [comment]
Hi Thomas,

It looks like you are pointing to the template files FullEnvironmentSetup.json and FullEnvironmentSetup.param.json

You should point to the files **FullEnvironmentSetupMerged.json** and **FullEnvironmentSetupMerged.param.json** i.e. the **"...Merged**" term is present in the file names.

Are you following the steps and video available here https://microsoft.github.io/PartsUnlimited/basic/cd.html ?

Thanks Again,
Eamonn
Eamonn

**Comment by winterwy** [comment]
Hi Eamonn,

You are right. I made a stupid mistake. 
I correct the template file and this time I finish the whole test. 

Thank you very much.

Thomas Yang
