### ISSUE TITLE
"Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)"

### ISSUE THREAD

**Issue by PHBeagle** [Microsoft/PartsUnlimited#134]
### Title
> Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)

### Functional impact
Results in solution failing to build.

### Minimal repro steps
Following directions from [here](https://microsoft.github.io/PartsUnlimited/basic/GettingStarted.html) under the "Set up your machine" and "Get the source code".

1. Installed Visual Studio 2017 (enterprise).
2. Install Azure Power Shell (irrelevant for this issue)
3. Install NodeJS (8.9.4 LTS rather than 6.11.3 LTS that the article mentioned)
4. Install bower and grunt.
5. Clone source code from [PartsUnlimited](https://github.com/Microsoft/PartsUnlimited.git)
6. Build solution

### Expected result
Successful build.

### Actual result
Build failed with error message - _"Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)"_

### Further technical details
Running a Windows 10 VM in Azure.
Located [this](https://github.com/jakearchibald/wittr/issues/20) issue which indicated to update the gulp-sass version to 3.1.0.  When I did a search of the solution, "gulp-sass" was only in the readme.  But I did notice that `npm install node-sass` did result in a couple warnings.  Namely that it could not find `c:\repos\PartsUnlimited\package.json`.

```
c:\repos\PartsUnlimited>npm install
npm WARN saveError ENOENT: no such file or directory, open 'c:\repos\PartsUnlimited\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\repos\PartsUnlimited\package.json'
npm WARN PartsUnlimited No description
npm WARN PartsUnlimited No repository field.
npm WARN PartsUnlimited No README data
npm WARN PartsUnlimited No license field.

up to date in 1.344s

c:\repos\PartsUnlimited>npm --version
5.6.0

c:\repos\PartsUnlimited>node --version
v8.9.4

```

I did also go through the `git clean -fdx` step as well to no avail.

**Comment by eamonnk** [comment]
Hi 

Can you try open up a **cmd** or **Powershell** window as administrator, go to the repo where the PartsUnlimitedWebsite src folder is located i.e. **C:\<repository path>\PartsUnlimited\src\PartsUnlimitedWebsite** then run the below command and try again to build the solution.

npm rebuild node-sass 

If you still get errors, check the version of node.js installed, if its not v6 but ver 8x, you could uninstall the 8x version thats currently installed and install ver 6.12.3 from the node.js LTS schedule page. Then try build the solution again.

Theres also an updated page available for this as well, https://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-PUsetupwithVS2017.html. which has more details then the page you're currently looking at. It has a bit more detail for errrors which might help.

If its still not building after trying those things let us know and will have another look.

Thanks,
Eamonn

**Comment by PHBeagle** [comment]
@eamonnk Thank you!  I can now build and debug the solution.

What I did:

1. Followed the directions on the updated page ("PandP").  That has better instructions and does, in fact, say NOT to use NodeJS 8x.
2. Uninstalled NodeJS 8x
3. Installed NodeJS 6.12.3
4. Cloned solution again to a different repository.
5. Ran `npm rebuild node-sass` due to error (the link has info about the error message).
6. Build solution.  All is now good.

This issue is resolved.  Thanks again!

**Comment by ghernandezfortes** [comment]
With "yarn add node-sass" worked for me

**Comment by DaFunkyAlex** [comment]
That worked for me:
```
npm --depth 9999 update
npm rebuild node-sass
```

**Comment by waqar-imtiaz** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

Thanks, this works for me :)

**Comment by theonlyalterego** [comment]
npm --depth 9999 update
npm rebuild node-sass

This also worked for me!

**Comment by kevindrc** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

This also worked for me! Thanks a lot, you saved my day !

**Comment by YannickNinot** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

Dosent work for me. She still block and dont move ...

**Comment by jsbimra** [comment]
what npm --depth 9999 update is doing ?

**Comment by vblain** [comment]
So actually paid to do my DevOps cert, but can't get this to work. I tried everything clean install. Node version 6.12.3 and still getting error 134 when grunt does the bower install. Also ran all the commands above, and deleted repo multiple times.

**Comment by vblain** [comment]
In case someone else had problem with Grunt Task Runner after following all the direction above. Please see this link https://developercommunity.visualstudio.com/content/problem/314581/gulpfilejs-fails-in-task-runner-in-visual-studio-2.html . Basically do this  go to Tools -> Options -> Projects and Solutions -> Web Package Management -> External Web Tools and move the $(PATH) entry above $(VSInstalledExternalTools). Restart VS 2017, and voila grunt task runner no longer using the wrong version of Node. It would seem that task runner will run the latest version of Node even if you install Node 6. Fixed everything for me. PS: you will still need to rebuild node-sass

**Comment by naveen-me** [comment]
remove node_modules folder
run
npm i

**Comment by kr4ckhe4d** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

Thank you it worked. Could you explain what the first line does?

**Comment by rusrc** [comment]
> > That worked for me:
> > ```
> > npm --depth 9999 update
> > npm rebuild node-sass
> > ```
> 
> Thank you it worked. Could you explain what the first line does?

Just take a loot at package.json file after the command processed. All stuff updated there for latest versions.

**Comment by kuige** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

In my case, only run `npm --depth 9999 update`, then the newest `node-sass` binary is redownloaded, no need for `npm rebuild node-sass`.

**Comment by namphd00769** [comment]
npm --depth 9999 update
npm rebuild node-sass 
Thank you, That worked for my project.

**Comment by MujahidAbbas** [comment]
npm --depth 9999 update
npm rebuild node-sass
This worked for me. Thank you!

**Comment by gabrielp16** [comment]
npm --depth 9999 update
npm rebuild node-sass

Thanks a lot !!! 
It really works

**Comment by BizzottoClaudio** [comment]
`npm --depth 9999 update`
ok
`npm rebuild node-sass`
did not worked
but at the end i was finally able to compile again

**Comment by ShrishtiChouksey30** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

**Worked for me too.**

**Comment by thanhkhanhcntt** [comment]
npm --depth 9999 update
npm rebuild node-sass

It's really worked. Thanks

**Comment by herico** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

It's really worked, Huge thank you

**Comment by Exteriordemonic** [comment]
> With "yarn add node-sass" worked for me


Worked for me

**Comment by johnworthley** [comment]
How long does npm --depth 9999 update take to run? 5 minutes in and the console shows nothing.

**Comment by ShreeSthapit** [comment]
> With "yarn add node-sass" worked for me

Worked For Me

**Comment by malik430** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

Work for me thank you

**Comment by manglide** [comment]
In my case, i had nvm installed, and was using node 11.10.1 on MinGW, once i switched back to node 8.9.4, it worked and the error went away.

**Comment by byejune** [comment]
> With "yarn add node-sass" worked for me

Worked for me. thanks.

**Comment by Shubham819** [comment]
I am using node 12.1.0 version, angular 8.2. 14 and node-sass 4.13.0
Still facing the issue.

**Comment by mskashef** [comment]
> 
> 
> npm --depth 9999 update
> npm rebuild node-sass
> Thank you, That worked for my project.

I have the same problem but these commands do not work for me.
`npm --depth 9999 update` takes a lot of time and does nothing (so I stop it)
and `npm rebuild node-sass` does nothing too.
and my error: 
```
ERROR in ./src/App.module.css (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js!./src
/App.module.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.0
    at module.exports (F:\MK\MyProjects\WebStorm\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (F:\MK\MyProjects\WebStorm\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at getDefaultSassImplementation (F:\MK\MyProjects\WebStorm\mashqeshq\node_modules\sass-loader\dist\utils.js:42:10)
    at getSassImplementation (F:\MK\MyProjects\WebStorm\mashqeshq\node_modules\sass-loader\dist\utils.js:50:30)
    at Object.loader (F:\MK\MyProjects\WebStorm\mashqeshq\node_modules\sass-loader\dist\index.js:34:59)
 @ ./src/App.module.css 2:26-197 43:4-64:5 46:18-189
 @ ./src/App.js
 @ ./src/index.js
```

> 
> 
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

**Comment by RawsonBpo** [comment]
npm --depth 9999 update
npm rebuild node-sass
It took a long time but it works thank you

**Comment by Cbooogdan** [comment]
I am using Vue 4.5.4 and I got this error on `yarn serve`, I fixes this with just running `yarn` and again `yarn serve`.

**Comment by zhicheng-Fu** [comment]
npm uninstall node-sass
npm install node-sass
its worked on mac osx 11  node 13

**Comment by oybek9508** [comment]
This shows that the version of node-sass you are trying to run is not compatible with the version of node installed. So you need to run 
> npm rebuild node-sass
and if this does not work, you should run the following command
> npm uninstall node-sass && npm install node-sass  (with -g if your node-sass installed globally)

**Comment by decpk** [comment]
If the problem still exists then first **uninstall** node.js and **reinstall** node. It works for me after 3 hours of struggle. Read every answer on SOF. Did almost everything that GitHub users said. But reinstalling works like a charm, on the first go.

**Comment by ymzEmre** [comment]
> That worked for me:
> 
> ```
> npm --depth 9999 update
> npm rebuild node-sass
> ```

Thank you, Worked for me.
