### ISSUE TITLE
CS0006	Metadata file 'D:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\bin\Debug\netcoreapp2.0\PartsUnlimitedWebsite.dll' could not be found

### ISSUE THREAD

**Issue by vhusker** [Microsoft/PartsUnlimited#135]
I am working through the getting started guide here:  https://microsoft.github.io/PartsUnlimited/basic/GettingStarted.html

Everything went great until I went to build the solution, where I got the following errors and warnings:
![image](https://user-images.githubusercontent.com/6845844/35653029-cfb37426-06ab-11e8-8f13-50cd33160313.png)

'D:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\bin\Debug\netcoreapp2.0\PartsUnlimitedWebsite.dll' could not be found	PartsUnlimited.UnitTests D:\Repos\PartsUnlimited\test\PartsUnlimited.UnitTests\CSC

Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (59)	PartsUnlimitedWebsite	D:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\EXEC	

Task "sass" not found. Use --force to continue.	PartsUnlimitedWebsite	D:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\EXEC

MSB3073	The command "grunt" exited with code 3.	PartsUnlimitedWebsite	D:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj	

I have followed the steps in the article to clean out the files and re-download them, and that hasn't changed anything.  Running Visual Studio as Administrator also didn't make any difference.

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Visual Studio:
Microsoft Visual Studio Enterprise 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA205
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA205
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA205
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17320.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.2000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.2000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.2000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17320.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17320.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17320.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17320.1
Profiling support for Python projects.

R Tools for Visual Studio   1.3.31108.1213
Provides project system, R Interactive window, plotting, and more for the R programming language.

Redgate ReadyRoll   1.16.18018.7798
Extend DevOps processes to your SQL Server databases and safely automate database deployments.
    
Visit https://www.red-gate.com/readyroll for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.
  
This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation. 
Visual Studio is a registered trademark of Microsoft Corporation. 

ReadyRoll contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
    

Redgate SQL Prompt   9.0.7.3692
Write, format, and refactor SQL effortlessly

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0

**Comment by vhusker** [comment]
This is the output from task runner explorer: 
C:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite> cmd.exe /c grunt -b "C:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite" --gruntfile "C:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\Gruntfile.js" default --color
Loading "sass.js" tasks...ERROR
>> Error: Missing binding C:\Repos\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-48\binding.node
>> Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x
>> 
>> Found bindings for the following environments:
>>   - Windows 64-bit with Node.js 5.x
>> 
>> This usually happens because your environment has changed since running `npm install`.
>> Run `npm rebuild node-sass` to build the binding for your current environment.
Warning: Task "sass" not found. Use --force to continue.
Aborted due to warnings.
Process terminated with code 3.

**Comment by vhusker** [comment]
I eventually was able to get this working.  I am writing a blog post on it tomorrow and will post the link here.  It was quite the adventure.

**Comment by vhusker** [comment]
It also didn't help that the link from the eDX course took me to here:  https://microsoft.github.io/PartsUnlimited/basic/GettingStarted.html instead of to here: https://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-PUsetupwithVS2017.html

**Comment by eamonnk** [comment]
Hi, 

Thanks for posting the issue and sorry for the experience you had with the lab and the delay getting back. We've gone back and updated the course lab links and published updates to the lab tasks as well on the GitHub pages site which should address the issues you encountered and help get around any future problems with them. 

If you encounter any other problems just let us know and we'll take a look.

Thanks Again,
Eamonn
