### ISSUE TITLE
Visual Studio 2017 can't Install Required Bower Packages (DevOps200.1x Lab1- PartsUnlimited Setup with Visual Studio)

### ISSUE THREAD

**Issue by dingliu** [Microsoft/PartsUnlimited#151]
Following the lab steps in [DevOps200.1x Lab1- PartsUnlimited Setup with Visual Studio](https://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-PUsetupwithVS2017.html).

### Functional impact

In task 3, after opening the **`PartsUnlimited.sln`** file in Visual Studio 2017, the IDE can't install the required bower packages. The lab can't proceed to the next step.

### Minimal repro steps

1. Create a **Visual Studio Community 2017 on Windows Server 2016 (x64)** VM in Azure
2. In the VS2017 VM, follow the lab steps provided in [instructions page](https://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-PUsetupwithVS2017.html), to task 3 step 3

### Expected result

There is no errors listed under the six projects of the PartsUnlimited Solution, particularly under dependencies

### Actual result

Under the dependencies of **`PartsUnlimitedWebsite`** project, all the required bower packages are not installed.

![bower-package-warnings](https://user-images.githubusercontent.com/888873/42458204-6eaab7f0-8367-11e8-8259-fbe6f32e40c7.png)

### Further technical details

When trying to restore bower packages, there are error messages in output pannel indicating **requests to https://bower.herokuapp.com/packages/ failed with code 502**.

![bower-package-install-requests-fail-502](https://user-images.githubusercontent.com/888873/42458219-777afd04-8367-11e8-9b26-3f7543382c52.png)

**Comment by dingliu** [comment]
It is because of Bower is deprecating their registry hosted with heroku. http://bower.herokuapp.com/ wont be accessible any more or it might be down intermittently there by forcing users to new registry.

The solution is to create a **`.bowerrc`** file with the following data

```JSON
{
  "registry": "https://registry.bower.io"
}
```

in the `<PATH>/<to>/PartsUnlimited/src/PartsUnlimitedWebsite/` folder.

There is a `bower.json` file in that folder.

All credits go to [Nithin Baby's answer in StackOverflow](https://stackoverflow.com/a/51020318).

I'm submitting a pull request.

**Comment by eamonnk** [comment]
Thanks for taking the time to investigate and submitting the solution in a PR, and apologies for the delay getting back.  It has been tested and verified it is working successfully and the PR has been merged into the master branch and is live now.

Thanks Again,
Eamonn

**Comment by dingliu** [comment]
You're very welcome. I'm closing this issue.
