### ISSUE TITLE
"Continuous Delivery with Windows Containers and VSTS" Lab is too broken to fix with a pull request

### ISSUE THREAD

**Issue by gavincampbell** [microsoft/PartsUnlimited#157]
This [lab](https://github.com/Microsoft/PartsUnlimited/blob/gh-pages/_posts/2018-01-08-200.4x-ConfigMgmt-CDwithWindowsContainersandVSTS.md) has a few problems, mostly caused by specifying the container name *iiscntr1* in task 5, step 6. This means that task 5, step 16 ("You should run this a couple of times") will fail on the second and subsequent runs, as the container is started on the build agent itself and not torn down between runs - the tasks to do this are disabled in task 5, steps 7 and 8. 

Task 6 will also fail, as the container name is still the same and there are no prerequisite steps to tear down the environment.

Of course, allowing the name to be assigned automatically will cause task 7 to fail due to task 5, steps 7 and 8 also failing.

Don't think I can fix this in a pull request without changing the intent of the lab exercise.

**Comment by eamonnk** [comment]
Thanks for posting, had a look at it and yeah there's some issue with this lab, we're working on updates at the moment, will probably take into tomorrow before that's complete but will post back here to let you know when its updated. 

Thanks Again,
Eamonn

**Comment by eamonnk** [comment]
Hi, 

Just FYI that am not forgetting this issue, have been looking at another issue which arose but will get back into this now and will let you know as soon as I have a resolution.

Thanks,
Eamonn

**Comment by eamonnk** [comment]
Hi Again, 

Sorry for the delay getting back on this, had what looked like a finished update but ran into some other parts if it needing changing.  I will have an update this week on it and let you know when its done.

Thanks Again,
Eamonn

**Comment by eamonnk** [comment]
Hi, 

Apologies for the long delay getting back on this. The lab has finally been updated [Continuous Delivery with Windows Containers and Azure Devops](http://microsoft.github.io/PartsUnlimited/configmgmt/200.4x-ConfigMgmt-CDwithWindowsContainersandVSTS.html). A good few changes have been made to the original lab to overcome the issues so it should be up and running now and working as expected.

Thanks,
Eamonn
