### ISSUE TITLE
VSTS CI Task "dotnet restore, build, test and publish" fails with errors

### ISSUE THREAD

**Issue by Casey-Rickwood** [Microsoft/PartsUnlimited#159]
Hi, 
I am getting the below error message with the VSTS CI Task "dotnet restore, build, test and publish".  I have also set the BuildConfiguration variable to release. Is there something else I am missing?

**Error Message:**
The test source file "D:\a\1\s\test\PartsUnlimited.UnitTests\bin\release\netcoreapp2.0\PartsUnlimited.UnitTests.dll" provided was not found.

Set-Content : Could not find a part of the path 'D:\a\1\a\Publish\manifest.xml'.
At D:\a\1\s\build.ps1:49 char:1
+ Set-Content -Path $manifestFile -Value $sourceManifest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\a\1\a\Publish\manifest.xml:String) [Set-Content], DirectoryNotFoundE 
   xception
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand

Process completed with exit code 1 and had 2 error(s) written to the error stream.

**Comment by spaikles** [comment]
Hi It seems that you are suffering from a issue that was fixed this weekend (at least after I re-downloaded the code on Monday).

Try getting the repo in VSTS again.

**Comment by Casey-Rickwood** [comment]
Hi Spaikles,
Thanks a lot for the advice as I re-cloned the VSTS again and now everything now works.
Casey
