### ISSUE TITLE
Provision-lab-textual-workflow Runbook Workflow script error

### ISSUE THREAD

**Issue by Mukhazul** [Microsoft/PartsUnlimited#164]
Not sure if this has been addressed or even if this is the right place to discuss this issue, but when I try and run the workflow script "Provision-lab-textual-workflow" for step 3 on the "Azure Automation Runbook Deployment" lab, I get a warning message which is stopping the Runbook from running to completion.

The warning message says:

56f8b139-52b7-4ef9-a9f3-cb804aa02779:[localhost]:Breaking changes in the cmdlet 'New-AzureRmVirtualNetwork' :
56f8b139-52b7-4ef9-a9f3-cb804aa02779:[localhost]:- "The output type 
'Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork' is changing"
 - The following properties in the output type are being deprecated :
 'EnableVmProtection'

**Comment by eamonnk** [comment]
Hi,

Yeah, this is the right place to post the issue. I just ran through the lab and see that same issue. Its a bit odd, I'll have to dig some more into it and will post back as soon as I have some more details.

Thanks,
Eamonn

**Comment by Alaabahr** [comment]
Hi, I'm facing the same. Any updates?

**Comment by eamonnk** [comment]
Hi Alaabahr, 

Sorry for the delay getting back, am looking at this now and will get back to you later today with an update.

Thanks,
Eamonn

**Comment by tompatib** [comment]
Hi Eamonn,

I'm about to finish this course soon, would appreciate if this could be fixed in the coming days. 

Regards,
Tibor

**Comment by eamonnk** [comment]
Hi All, 

Took longer than expected to chase it down, but this is now fixed and an update published. There are  two parts to the fix

1) An Azure module update caused the script to fail. Steps in the lab [Azure Automation Runbook Deployments](http://microsoft.github.io/PartsUnlimited/iac/200.2x-IaCM01AzureAuto.html) have been updated to give specific details about which Azure module version to use and how to do that. 


2) The subnet config wasn't getting applied to the virtual network and that was also causing an issue. An additional cmdlet was added to the workflow file to ensure the subnet config gets applied to the vnet. The workflow provision file has been updated here **Labfiles\Devops200.2x-InfrastructureasCode\Mod01\Provision-lab-textual-workflow-v1.ps1**, as per the lab steps.

The message about a change in output type, isn't causing any issues, its just a notification of a change that's coming, and the parameter isn't used in the script either regardless.

Anyway, the update has been tested and its good to go. 

Thanks for flagging and let us know if theres any further issues with it,
Eamonn

**Comment by tompatib** [comment]
Thanks it works finally. I had problem afterwards the deprovision script, it was completed but the RG1 haven't been removed. I will check that later.

**Comment by eamonnk** [comment]
Great, glad to hear it is working. I just ran through the deprovisioning and it worked fine, deleted all resources and also the resource group. Perhaps a resource was being accessed or locked in some way... sure let us know how it goes.

Thanks Again,
Eamonn
