### ISSUE TITLE
Deploy app with Chef on Azure - Video not working

### ISSUE THREAD

**Issue by YvonneArnoldus** [Microsoft/PartsUnlimited#167]
If I start the Lab Video on [Deploy app with Chef on Azure](https://microsoft.github.io/PartsUnlimitedMRP/iac/200.2x-IaC-DeployappwithChefonAzure.html), I get the following error: 

> AuthenticationFailedServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f01b377f-401e-0094-1caf-7ae171000000 Time:2018-11-12T17:45:20.1914450ZSigned expiry time [Wed, 31 Oct 2018 19:21:15 GMT] must be after signed start time [Mon, 12 Nov 2018 17:45:20 GMT]

**Comment by eamonnk** [comment]
Hi Yvonne, 

Sorry for the delay getting back, the video is back running now again, there was an authentication issue with the url and storage location. It's been fixed so should be fine now.

Thanks,
Eamonn
