### ISSUE TITLE
dotnet restore, build, test and publish 3 Mistake

### ISSUE THREAD

**Issue by ecostella2010** [Microsoft/PartsUnlimited#173]
I have 3 mistakes in the step nine of the task four, please someone can help me: 

https://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-CICDQuickstartwithVSTS.html

1) The test source file "D:\a\1\s\test\PartsUnlimited.UnitTests\bin\debug\netcoreapp2.0\PartsUnlimited.UnitTests.dll" provided was not found.

2) Set-Content : Could not find a part of the path 'D:\a\1\a\Publish\manifest.xml'.
At D:\a\1\s\build.ps1:49 char:1
+ Set-Content -Path $manifestFile -Value $sourceManifest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\a\1\a\Publish\manifest.xml:String) [Set-Content], DirectoryNotFoundE 
   xception
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand

3) Process completed with exit code 1 and had 2 error(s) written to the error stream.

**Comment by krupaltandel** [comment]
I'm having the same issue. Does anyone have any clue on how to resolve this? LIke KKnapik says the VS2017 agent has been updated to .NETcore framework 2.2.102.
Which version of framework would be compatible with this build? There is a way to choose the version in the pipeline if I'm not wrong.

**Comment by krupaltandel** [comment]
After changing the .NET Framework version number to 2.1 on the build.ps1 file, it worked on my own agent. Still haven't been able to figure out for the Hosted VS2017 agent.

**Comment by omogrosso** [comment]
Any solution for this for the moment? i have the same problem :S i cant practice my lab :S

**Comment by fredrikengseth** [comment]
Also struggling with the same issue :s

**Comment by eamonnk** [comment]
Hi All, 

Apologies for the delay following up. This is being loked at now and will gte back with an update shortly.

**Comment by eamonnk** [comment]
Hi All, 

An update has been pushed for the PartsUnlimited app and its is now building successfully again in AzDev with the hosted 2017 build agent. There's a related issue still being worked through for local builds with Visual Studio 2017,but it should be building fine now in AzDev.

Thanks,
Eamonn

**Comment by fredrikengseth** [comment]
Can confirm that the build in Azure DevOps now works fine. Thanks Eamonn :-D

**Comment by eamonnk** [comment]
Hi Again,

Just fyi that a fix has been pushed for the vs2017 scenario also, so the app should be building fine now both in AzDev and also vs2017.

Thanks Again,
Eamonn
