### ISSUE TITLE
Bower:install task installs the packages but does not copy output to www/lib

### ISSUE THREAD

**Issue by rroman81** [Microsoft/PartsUnlimited#174]
Based on my experimentation, i noticed that by default grunt-bower-task no longer copies the output to the target folder unless the gruntfile is modified as follows

```js
        bower: {
            install: {
                options: {
                    targetDir: "wwwroot/lib",
                    install: true,
                   copy: true,
                    layout: "byComponent",
                    cleanTargetDir: "true"
                }
            }
        }
```
I see this issue with node 11.7, npm 6.6, bower 1.8.7, and grunt-cli v1.3.2

I can prepare a PR real quick to fix this but want to get someone else's opinion on it.

**Comment by eamonnk** [comment]
This has been rolled in with the broader .NET 2.2. update you submitted, so is in the source files now.

Thanks Again,
Eamonn
