### ISSUE TITLE
Build Error-error MSB3073: The command "npm install -g grunt-cli" exited with code 243.

### ISSUE THREAD

**Issue by velugovindan** [Microsoft/PartsUnlimited#178]
Hi,

While building the code am facing below error. Please help me out to resolve the issue.

 npm WARN PartsUnlimited@0.0.0 No license field.
  
  added 394 packages from 218 contributors and audited 1931 packages in 142.992s
  found 7 vulnerabilities (2 low, 3 moderate, 2 high)
    run `npm audit fix` to fix them, or `npm audit` for details
  npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
  npm ERR! path /usr/local/lib/node_modules
  npm ERR! code EACCES
  npm ERR! errno -13
  npm ERR! syscall access
EXEC : npm ERR! error : EACCES: permission denied, access '/usr/local/lib/node_modules' [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
  npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
  npm ERR!   stack:
  npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
  npm ERR!   errno: -13,
  npm ERR!   code: 'EACCES',
  npm ERR!   syscall: 'access',
  npm ERR!   path: '/usr/local/lib/node_modules' }
  npm ERR! 
  npm ERR! The operation was rejected by your operating system.
  npm ERR! It is likely you do not have the permissions to access this file as the current user
  npm ERR! 
  npm ERR! If you believe this might be a permissions issue, please double-check the
  npm ERR! permissions of the file and its containing directories, or try running
  npm ERR! the command again as root/Administrator (though this is not recommended).
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/vsts/.npm/_logs/2019-03-26T18_38_35_823Z-debug.log
/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj(40,5): error MSB3073: The command "npm install -g grunt-cli" exited with code 243.

Build FAILED.

../src/binding.cpp(246,39): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/binding.cpp(254,40): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(111,5): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(111,5): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/create_string.cpp(17,37): warning GB95BEE83: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
../src/callback_bridge.h(162,3): warning GCCCE6F31: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations] [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
EXEC : npm ERR! error : EACCES: permission denied, access '/usr/local/lib/node_modules' [/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj]
/home/vsts/work/1/s/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj(40,5): error MSB3073: The command "npm install -g grunt-cli" exited with code 243.

**Comment by eamonnk** [comment]
Hi, 

Are you following the steps on the page [PartsUnlimited Setup with Visual Studio](http://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-PUsetupwithVS2017.html) ?

Those lab steps have just been updated to include a step to install .NET Core 2.2, and if you have a look at the section **Build Errors and Solutions** it provides details you can look at to help troubleshoot, primarily addressing node-sass errors can help, although there are other pointers there also. 


I just tried a clean build this morning and it built fine, so its working as expected, and the above pointers should help you get it working but let us know how you get on.

Thanks,
Eamonn

**Comment by velugovindan** [comment]
Hi Eamonnk,

Are you following the steps on the page PartsUnlimited Setup with Visual Studio ?
 NO.

Am building the code(Parts Unlimited) directly in Azure Devops itself. Please help me how to resolve the issue.

Thanks,
Velu G

**Comment by velugovindan** [comment]
Hi Eamonnk,

I tried to building the project with both json and Project file but it's failed below are the two different  errors.

1.PartsUnlimited/templates/build definitions/PartsUnlimited-CI.json- 

error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

2..PartsUnlimited/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj-

 error MSB3073: The command "npm install -g grunt-cli" exited with code 243.

**Comment by eamonnk** [comment]
Hi Again, 

Ran through the PartsUnlimited [CI](http://microsoft.github.io/PartsUnlimited/cicd/200.3x-CICD-M01-CIwithVSTS.html) and [CD](http://microsoft.github.io/PartsUnlimited/cicd/200.3x-CICD-M03-CDwithVSTS.html) labs, i.e. build and release in Azure DevOps, and the PartsUnlimited app built and deployed fine to Azure for me. Can you let me know which lab you are following? it may be something in a specific lab step that has changed.

Thanks,
Eamonn

**Comment by velugovindan** [comment]
Hi ,

Am not using any lab procedure i just want to build the Parts unlimited code in Azure Devops.
Is it necessary to follow the lab procedure?
Am referring the below lab:
http://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-CICDQuickstartwithVSTS.html

Note: I skipped all the VSTS steps.

I will mention my below steps. Please correct me if anything i want to change.

1.  I clone the code to my git hub repository by copying the URL.

2. Started to build the code using ASP.net core .

3. Build thrown out with below error.

MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

4. Edited the YML file by adding the below paths (.PartsUnlimited/templates/build definitions/PartsUnlimited-CI.json ) and (PartsUnlimited/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj)but still facing issue.

 Below are the two different errors.

1.PartsUnlimited/templates/build definitions/PartsUnlimited-CI.json-

error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

2..PartsUnlimited/src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj-

error MSB3073: The command "npm install -g grunt-cli" exited with code 243.

Thanks, 
Velu G

**Comment by eamonnk** [comment]
Hi Again, 

Yeah, I'd recommend following the lab steps at least at a high level, as it will call out some gotcha's or config required as you go which may not be immediately obvious.

In the lab steps the build is called by a Powershell script, *build.ps1*, the .net core 2.2 framework is specified as part of that, as well as some test runs and artifact generation details. So the build process steps provided don't use the ASP .Net Core or any other built in AzDev build tasks, am sure you could get it working, but there would be  some changes/tweaks needed. The main purpose of the app is really just to provide a real world example to use in the pipeline, how the app is actually built isn't a huge focus, its more the pipeline process and construction.


I'd recommend to follow the [QuickStart lab](http://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-CICDQuickstartwithVSTS.html ), or the [CI Lab](http://microsoft.github.io/PartsUnlimited/cicd/200.3x-CICD-M01-CIwithVSTS.html) to get the build up and running and then the second part of the QuickStart lab, or the [CD Lab](http://microsoft.github.io/PartsUnlimited/cicd/200.3x-CICD-M03-CDwithVSTS.html). They should have enough detail to allow you get it building successfully.


Thanks Again,
Eamonn

**Comment by velugovindan** [comment]
Hi Eamonn,

Thanks for your advise , The build is working fine.

Can i use the same(parts Unlimited ) project in Jenkins? 

Thanks,
Velu G

**Comment by eamonnk** [comment]
Hi, 

I haven't set up the PU app with Jenkins, it should work but there is a different app used for Jenkins that is java based. The labs are listed below

[Setup Jenkins in Azure](http://microsoft.github.io/PartsUnlimitedMRP/cicd/200.3x-CICD-SetupPUwithJenkins.html), 
[Continuous Integration with Jenkins](http://microsoft.github.io/PartsUnlimitedMRP/cicd/200.3x-CICD-CIwithJenkins.html)
and
[Continuous Deployment with Jenkins](http://microsoft.github.io/PartsUnlimitedMRP/cicd/200.3x-CICD-CDwithJenkins.html)

Thanks,
Eamonn

**Comment by eamonnk** [comment]
closing as issue addressed
