### ISSUE TITLE
Problem with Deployment.json 

### ISSUE THREAD

**Issue by sakriel91** [Microsoft/PartsUnlimited#179]
I am in the middle of : http://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-CICDQuickstartwithVSTS.html

And there seems to be an error with Deployment.json file:
JSON.parse: bad control character in string literal at line 1 column 4097 of the JSON data

It appeared after i tried to import deployment.json.

Regards,

**Comment by eamonnk** [comment]
Hi, 

A new file has been pushed up to the repo, with a new filename, **PUReldef1.json**, and the lab step detail has also been updated, *templates\release definitions\PUReldef1.json*.

Can you try with this updated json

Thanks,
Eamonn

**Comment by sakriel91** [comment]
Hello!

Thanks for quick responce. It fixes the problem. But now i encountered another problem...

2019-04-04T08:49:39.2802057Z Checking if the following resource group exists: XVGroup89377.
2019-04-04T08:49:39.6442247Z Resource group exists: true.
2019-04-04T08:49:39.6444252Z Creating deployment parameters.
2019-04-04T08:49:39.6857554Z ##[error]Error: Could not find any file matching the template file pattern

Do you know what might be the problem?

**Comment by sakriel91** [comment]
And besides that git push do not trigger build :)

**Comment by eamonnk** [comment]
I'll step through it and get back to you later today on it,

Thanks for letting us know!
Eamonn

**Comment by sakriel91** [comment]
Hi, Any news?

**Comment by eamonnk** [comment]
Hi,

Sorry for the delay getting back, am still looking at it, but expect to have an update to push out later today/tomorrow at the latest.

Thanks Again,
Eamonn

**Comment by eamonnk** [comment]
Hi, 

An updated release definition template has been pushed live, which should address the problems you encountered. The lab steps have alos been modified slightly for some additional pointers. Its not a complete update, theres still some legacy screenshots and detaisl, but there should be enough detail there to import the definition and get it working.

It's been tested and works fine here but let me know if its working for you.

Thanks Again,
Eamonn

**Comment by eamonnk** [comment]
closing as fixed
