### ISSUE TITLE
Port master to beta5

### ISSUE THREAD

**Issue by EMaher** [Microsoft/PartsUnlimited#22]
Current the master branch works against beta4.  However, with the release of Visual Studio 2015, the default version of .net for ASP.NET 5 products is the beta5 version.  Master should be updated to reflect that.

**Comment by MaherJendoubi** [comment]
why not port it directly to beta 6 or beta 7 which will be released next week according to asp.net 5 roadmap?

**Comment by twsouthwick** [comment]
We already had beta5 working on another branch, this just merges it to master. Next steps will probably be to update it to beta 7.

**Comment by twsouthwick** [comment]
Made issue to track porting to beta 7: #27

**Comment by EMaher** [comment]
Code merged
