### ISSUE TITLE
Dependency xunit.runner.aspnet >= 2.1.0-beta1-* could not be resolved	

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/PartsUnlimited#23]
Hi,

I try to build and test this project. I use a brand new machine with Windows 10, Visual Studio 2015 Enterprise(RTM) with "dnvm install 1.0.0-beta4" and Microsoft Azure SDK for .NET (VS 2015) - 2.7.

We no longer download Visual Studio RC unless we don't have MSDN. It might cause problem when we try to do some hands on.

 I can build and deploy Azure. However, I still have this error.  I know xunit.runner.aspnet is outdated and truned into dnx. However, how to install this library?  I try this procedure but it didn't work.

https://www-1.nuget.org/packages/xunit.runner.aspnet/

Any ideas?

**Comment by TsuyoshiUshio** [comment]
Sorry, I just forget to dnvm use 1.0.0-beta4.  Now master is for 1.0.0-beta5. 
Now It works fine.

**Comment by EMaher** [comment]
@TsuyoshiUshio  Glad you figured out!  I'm going to close the issue since everything is working fine.
