### ISSUE TITLE
PartsUnlimited.MRP.sln vs PartsUnlimited.sln

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/PartsUnlimited#31]
What is the difference between PartsUnlimited.sln and PartsUnlimited.MRP.sln solutions?

**Comment by EMaher** [comment]
PartsUnlimited.sln is the solution with just the website.  PartsUnlimitied.MRP.sln has some extra projects that contain WebJobs and are used by https://github.com/Microsoft/PartsUnlimitedMRP.
