### ISSUE TITLE
Unable to create directory error

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/PartsUnlimited#53]
In this tutorial I seem to be having a problem with the MSBuild Arguments.  Without specifying  /p:PackageLocation all is well but I have no idea where the build was copied to.

**My arguments are:**
 /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="K:\agent\MyApp"

**Here are the error messages:**
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets (2954, 5)  
 Unable to create directory "K:\agent\MyApp\". Could not find a part of the path 'K:\agent\MyApp\'.
  
System.Exception: Unexpected exit code received from msbuild.exe: 1 
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeMSBuildCmdlet.ProcessRecord() 
at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by EMaher** [comment]
Could you give me a little more information.  To which tutorial are you referring?  Are you using the ASP.NET 4.6 MVC 5 version of the website or the ASP.NET 5 MVC 6 version of the website?

**Comment by Chiliyago** [comment]
Oh sorry, I thought this thread was for the HOL located at this URL

https://github.com/Microsoft/PartsUnlimited/blob/hands-on-labs/docs/HOL_PartsUnlimited_WebSite_Continuous_Integration/HOL_PartsUnlimited_WebSite_Continuous_Integration_with_Visual_Studio_Online_Build.md

**Comment by bspann** [comment]
Chiliyago - The HOL for Continuous Integration has, in my opinion, a type-o.  The author looks to me to be using a custom build server thus creating a share folder on the build server for drops.  If you are using the Hosted Build Agent, then substitute the following commands in the **MSBuild Arguments**:

/p:DeployOnBuild=true 
/p:WebPublishMethod=Package 
/p:PackageAsSingleFile=true 
/p:SkipInvalidConfigurations=true 
/p:PackageLocation="$(build.stagingDirectory)"

Then in the "Publish Build Artifacts" build task, place the following in the **Path to Publish**:
$(build.stagingDirectory)

That should work for you.

Thanks,

Brian

**Comment by dtzar** [comment]
Thanks for the response Brian.  Brian is correct that the $(Build.StagingDirectory) is an often recommended location to store the build and to put it into the argument.  This is better than the currently listed local path and I will update the HOL.  The best place to put the path is $(BuildConfiguration).  All variables can be found here FYI: https://msdn.microsoft.com/en-us/Library/vs/alm/Build/scripts/variables
