### ISSUE TITLE
MSBuild Definition Paramters invalid

### ISSUE THREAD

**Issue by hgoodrow** [Microsoft/PartsUnlimited#54]
When using the msbuild parameters in the article, the resulting build errors out with the following:
 
2016-02-18T18:03:59.6389793Z MSBUILD : error MSB1008: Only one project can be specified.
2016-02-18T18:03:59.6389793Z Switch: p:DeployOnBuild=true
2016-02-18T18:03:59.6399788Z For switch syntax, type "MSBuild /help"
2016-02-18T18:03:59.8519793Z ##[error]Process 'msbuild.exe' exited with code '1'.

Build parameters:
/p:DeployOnBuild=true 
/p:WebPublishMethod=Package 
/p:PackageAsSingleFile=true 
/p:SkipInvalidConfirations=true 
/p:PackageLocation="C:\Agent\HOL"

**Comment by EMaher** [comment]
Henry,  
Could I get a little more detail on which project you are using?  The one from the master branch or the one from aspnet45?  Are you following a specific lab?  
Thanks,
Elizabeth

**Comment by hgoodrow** [comment]
I was following the lab here: https://github.com/Microsoft/PartsUnlimited/blob/hands-on-labs/docs/HOL_PartsUnlimited_WebSite_Continuous_Integration/HOL_PartsUnlimited_WebSite_Continuous_Integration_with_Visual_Studio_Online_Build.md

I am happy to grant you access to my VSO instance.

**Comment by julienstroheker** [comment]
Hello Henry, did you insert the build parameters in an one line with only one space between each parameters ?

Like this :  
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="C:\Agent\HOL"

Thanks

**Comment by dtzar** [comment]
Sorry - these are more issues due to the invalid path which should have been fixed awhile ago.  you should use $(Build.StagingDirectory) instead of "C:\Agent\HOL"

**Comment by dtzar** [comment]
This has now been updated https://github.com/Microsoft/PartsUnlimited/blob/hands-on-labs/docs/HOL_PartsUnlimited_WebSite_Continuous_Integration/HOL_PartsUnlimited_WebSite_Continuous_Integration_with_Visual_Studio_Online_Build.md  Can you please see if you still have problems?

**Comment by dtzar** [comment]
I just verified this works and no response from @hgoodrow for 7 days now so closing.  Please let us know if you are still experiencing issues.

**Comment by mikepetty21** [comment]
I noticed the links posted on Feb. 19th and 25th are broken.

**Comment by dtzar** [comment]
Right - we changed the structure to move to the webpage here: http://aka.ms/pumrplabs
