### ISSUE TITLE
Can this demo web site be setup on local server

### ISSUE THREAD

**Issue by eliassal** [Microsoft/PartsUnlimited#64]
Hi, I downloaded this application followed all instructions, the solution restored everything and I was able to build in my local Visual studio. I hit "Start debug", eveyrhting compile and I get a Dos windos indicating that application is listening at http://localhost:5001 but nothing opens in my browser. I don't want to touch anything for the time being in my Azure account, so the question is this logic, can I run the application locally without going to azure?
Thanks

**Comment by mcpnet** [comment]
You need to open a browser and type "http://localhost:5001" in your browser. You should be able to see web page.

Absolutely you can run it locally without going to Azure. Above URL shows that it is running locally. That's really your local machine, not Azure.
What maybe is confusing you is the fact that you see Command Window (DOS window that you call it).
Nothing wrong there!!!!!
That's the beauty of the new ASP.NET CORE. It can run on anything, anywhere, even from that "little DOS window" that you call it, and no big "IIS" brother needed. :)

If you don't like it to run from your Command Window  ("DOS window") then change the Solution Platforms option. 
That's mean that you change dropdown value from "**Mixed Platforms**" option to maybe "**Any CPU**". Also change Debug Target (that Green Debug Arrow , START button) to maybe IIS Express option or any other available on your machine. You may have preselected "**Kestrel**" by default or something else.  Selecting "IIS" or "IIS Express" will force new browser window to open when you run solution.
But, you may try to start learning that you don't really need IIS nor IIS Express. Kestrel maybe will be enough for you.
Don't be lazy. Open your browser and type your local URL in the address bar, like it is showed in that  little "DOS" window. You may start liking that little Kestrel. Even if you run solution in IIS, Kestrel will be the one that executes things for you. No escape from it maybe.

Cheers. 

Happy "** A-NET-CORE-ing**" ....  or "**Kestrel-ing**" .... ,  whatever way you prefer to say it.

**Comment by dtzar** [comment]
Thanks for the reponse @mcpnet ! You can also run the aspnet45 branch local to your box too by going to the URL.

**Comment by eliassal** [comment]
thanks for your help, the site is running like a charm.

**Comment by eliassal** [comment]
By the way, is there any doc that can help undeerstand the architecture and new features used as it is developed with the most recent asp.net core 1 technology?
Thanks

**Comment by eliassal** [comment]
I started trying to understand, put a breakpoint on the line  
var sqlConnectionString = Configuration["Data:DefaultConnection:ConnectionString"]; in ConfigureServices as I am not able to see where this configuration is stored.
Problem, debugger breaks on the line but all "Step Into, Step Over......" are greyed out, hovering on "sqlConnectionString" gives no indication. 
Is this normal?

**Comment by mcpnet** [comment]
https://docs.asp.net/
The URL for ASP.NET Core documentation.
Not all documents are developed, you may see only placeholders for many.
Also, some documents need to be updated as they were written using "OLD" approach and OLD name for the product.
Keep in mind that this is still work in progress. Things still change even is past RC1 going to RC2.

About Connection string.
What you experience while running the application is ABSOLUTELY normal. 
That's the new feature that developers should appreciate. You don't need to have a real database, and in your case you don't have it.
You are using IN-MEMORY EF 7 feature in application and you don't need a connection string for it.
If you want to start using some real database then you will need to use a connection string.

**Comment by eliassal** [comment]
Thanks a lot for yoyr quick feedback, so as I am new to EF 7, which or how or what parameter indicate  that EF service should use In-Memory in the case of Partsunlimited

**Comment by mcpnet** [comment]
The fact that there is a no Connection String :)
It's that easy...
You want to build Context class without connection string, well, EF 7 will use in-memory database.
They assume that you will never use this in production as nothing gets stored permanently on any drive and in case of crash, power outage you will lost everything. 
Use it for development ONLY. :)

Check the code, section where is checking for Connection string in Startup.cs :

....
            var useInMemoryDatabase = string.IsNullOrWhiteSpace(sqlConnectionString); 
 
 
            // Add EF services to the services container 
            if (useInMemoryDatabase_ || runningOnMono) 
            { 
                services.AddEntityFramework() 
                         .AddInMemoryDatabase() 
                         .AddDbContext<PartsUnlimitedContext>(options => 
                         { 
                             options.UseInMemoryDatabase(); 
                         }); 
             } 
             else 
             { 
                 services.AddEntityFramework()                 
                         .AddSqlServer() 
                         .AddDbContext<PartsUnlimitedContext>(options => 
                         { 
                             options.UseSqlServer(sqlConnectionString); 
                         }); 
             }
