### ISSUE TITLE
Broken link in HOL_Continuous_Deployment_Release_Management.md

### ISSUE THREAD

**Issue by dburnison** [Microsoft/PartsUnlimited#67]
The "HOL - Parts Unlimited Website Continuous Integration with Visual Studio Team Services" link on the https://github.com/Microsoft/PartsUnlimited/blob/hands-on-labs/docs/HOL_PartsUnlimited_WebSite_Continuous_Deployment/HOL_Continuous_Deployment_Release_Management.md page is broken. 

I believe it should be a link to:
https://github.com/Microsoft/PartsUnlimited/tree/hands-on-labs/docs/HOL_Continuous_Integration

**Comment by dtzar** [comment]
PR just submitted to fix this.

**Comment by EMaher** [comment]
PR merged.  Closing the issue.
