### ISSUE TITLE
When is this going to be ported to ASP.net Core?

### ISSUE THREAD

**Issue by cashfoley** [Microsoft/PartsUnlimited#72]

**Comment by dtzar** [comment]
We're working on this now.  RC2 only came out a week ago and had significant tooling changes - please bear with us.

**Comment by cashfoley** [comment]
Thanks!  I'm doing a bake off of various configurations and deployment technologies.  Obviously Asp.Net Core going to PaaS Slots and Linux IaaS is top of the cool list!

**Comment by dtzar** [comment]
You can check out an early copy of the .Net Core RC2 implementation here until we get it merged into master: https://github.com/EMaher/PartsUnlimited/tree/emaher/upgradeToRc2

**Comment by cashfoley** [comment]
Thanks David!

**Comment by EMaher** [comment]
Okay, I have the website building, loading and showing product details at https://github.com/EMaher/PartsUnlimited/tree/emaher/upgradeToRc2.  The checkout scenario is still not working-- that is my next task.

**Comment by NVentimiglia** [comment]
What is the status on this ?

**Comment by dtzar** [comment]
The upgrade to RC2 has been completed PR #78 - hopefully we will have the .Net Core final upgrade in the near future.  Big leap to RC2 and hopefully shouldn't be much work to the final bits.  Going to close this issue out.
