### ISSUE TITLE
DNX design time process

### ISSUE THREAD

**Issue by eliassal** [Microsoft/PartsUnlimited#73]
Hi, I mnaged to download, compile and we site works fine. However, when I come back, fire VS, and  reopen the solution in VS, I get the following

The following error occurred attempting to run the DNX design time process(dnx-clr-win-x86.1.1.0-rc1-update1)
No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:56426
The DNX design time process provides intellisense, build..........check that the DNX version is properly isnstalled

Both, start debugging and Start with debugging items in the debugging menu are disabled.
I close the solution, reopen it, I don²t get this message and all buttons enabled and can run the website. 
What is the issue here? Thanks in advance

**Comment by dtzar** [comment]
This is getting ported to RC2 now, so tooling will be significantly different.  If you want to play with an early upgrade until we get it merged to master - go here: https://github.com/EMaher/PartsUnlimited/tree/emaher/upgradeToRc2

**Comment by dtzar** [comment]
This shouldn't be a problem anymore now we have #78 merged.  If so, please re-open or comment on this issue.  Thanks!
