### ISSUE TITLE
i could't restore the bower package

### ISSUE THREAD

**Issue by hiny2010** [Microsoft/PartsUnlimited#75]
i used the task runner explorer .run the "bower",it's always print 
>> Cleaned target dir F:\PartsUnlimited-master\PartsUnlimited-master\src\PartsUnlimitedWebsite\wwwroot\lib
Fatal error: Failed to execute "git clone https://github.com/aspnet/jquery-validation-unobtrusive.git -b v3.2.2 --progress . --depth 1", exit code of #-532462766
Process terminated with code 1.

**Comment by dtzar** [comment]
This is getting ported to RC2 now, so tooling will be significantly different.  If you want to play with an early upgrade until we get it merged to master - go here: https://github.com/EMaher/PartsUnlimited/tree/emaher/upgradeToRc2

**Comment by hiny2010** [comment]
i see .thanks
