### ISSUE TITLE
Faild to build solution using hosted agent in VSTS online.

### ISSUE THREAD

**Issue by DariuszPorowski** [Microsoft/PartsUnlimited#79]
**Error in the build stream:**
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
- Check application dependencies and target a framework version installed at:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App
- The following versions are installed:
1.0.0
- Alternatively, install the framework version '1.0.0-rc2-3002702'.

**dotnet --version on hosted server in VSTS online account**
1.0.0-preview2-003121

**Comment by dtzar** [comment]
Thanks for the heads up Dariusz.  Once we upgrade the app to the RTM version this should get resolved.  No ETA yet unfortunately :(

**Comment by julienstroheker** [comment]
@DariuszPorowski the code is now using DotNet Core 1.0 now.
Thanks
